language: node_js
node_js: 8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/node_modules'

script:
    - 'npm install'
    - 'npm run build'

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bsc0227@gmail.com
